from .labels import (
    SUBTASK1_ID_TO_NAME,
    SUBTASK1_LABELS,
    SUBTASK2_COLUMN_TO_NAME,
    SUBTASK2_COLUMNS,
    SUBTASK2_LABELS,
)

__all__ = [
    "SUBTASK1_ID_TO_NAME",
    "SUBTASK1_LABELS",
    "SUBTASK2_COLUMN_TO_NAME",
    "SUBTASK2_COLUMNS",
    "SUBTASK2_LABELS",
]
